// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelAPIListing.Migrations
{
    [DbContext(typeof(HotelApiContext))]
    [Migration("20260214202735_SeededCountriesAndHotels")]
    partial class SeededCountriesAndHotels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelAPIListing.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United States",
                            ShortName = "US"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Canada",
                            ShortName = "CA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "United Kingdom",
                            ShortName = "UK"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Congo D.R",
                            ShortName = "RDC"
                        },
                        new
                        {
                            Id = 5,
                            Name = "France",
                            ShortName = "FR"
                        },
                        new
                        {
                            Id = 6,
                            Name = "South Africa",
                            ShortName = "SA"
                        });
                });

            modelBuilder.Entity("HotelAPIListing.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "42 Sunset Blvd",
                            CountryId = 1,
                            Name = "Hotel California",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 Maple Street",
                            CountryId = 2,
                            Name = "Maple Leaf Inn",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "10 Downing Street",
                            CountryId = 3,
                            Name = "The Royal London",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Address = "456 Jungle Road",
                            CountryId = 4,
                            Name = "Congo Safari Lodge",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 5,
                            Address = "789 Champs-Élysées",
                            CountryId = 5,
                            Name = "Parisian Elegance",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 6,
                            Address = "321 Ocean Drive",
                            CountryId = 6,
                            Name = "Cape Town Retreat",
                            Rating = 4.2999999999999998
                        });
                });

            modelBuilder.Entity("HotelAPIListing.Data.Hotel", b =>
                {
                    b.HasOne("HotelAPIListing.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelAPIListing.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
